language: c
sudo: required
notifications:
  email: false

#before_install:

install: true

#before_script:

script: ./compile_archives.sh

#after_success:

#after_failure:

#before_deploy:

#deploy:
#  skip_cleanup: true

#after_deploy:

#after_script:


