# blacklist
branches:
  only:
    - /^RELEASE_.*$/

language: c
sudo: required
notifications:
  email: false

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y expect dos2unix
  - sudo apt-get install -y build-essential devscripts debhelper

install: true

#before_script:

script: ./compile_archives.sh

#after_success:

#after_failure:

#before_deploy:

#deploy:
#  skip_cleanup: true

#after_deploy:

#after_script:


