language: c

#before_install:

install: true

#before_script:

script: bundle exec ./compile_archives.sh

#after_success:

#after_failure:

#before_deploy:

#deploy:
#  skip_cleanup: true

#after_deploy:

#after_script:


